export type HseAlert = {
  id: string;
  tenantId: string;
  tenantName: string;
  moduleId: string;
  moduleName: string;
  site: string;
  projectId: string;
  projectName: string;
  title: string;
  source: string;
  severity: "Critique" | "Haute" | "Moyenne";
  status: "Ouvert" | "En cours" | "A verifier";
  dueDate: string;
  owner: string;
  recommendation: string;
};

export const hseAlerts: HseAlert[] = [
  {
    id: "alt-001",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "ppe",
    moduleName: "EPI",
    site: "San Pedro",
    projectId: "PRJ-SPD-001",
    projectName: "Terminal Vraquiers SP",
    title: "Masques FFP3 en rupture prochaine",
    source: "Inventaire EPI",
    severity: "Critique",
    status: "Ouvert",
    dueDate: "05/06/2026",
    owner: "K. Yao",
    recommendation: "Declencher une commande urgente et verifier les dotations respiratoires.",
  },
  {
    id: "alt-002",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "events",
    moduleName: "Evenements",
    site: "Abidjan",
    projectId: "PRJ-ABJ-001",
    projectName: "Autoroute Abidjan-Bassam",
    title: "Enquete incident grave non cloturee",
    source: "Declaration incident",
    severity: "Critique",
    status: "En cours",
    dueDate: "06/06/2026",
    owner: "A. Kouadio",
    recommendation: "Finaliser l'analyse causes racines et valider le plan d'actions.",
  },
  {
    id: "alt-003",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "actions",
    moduleName: "Actions",
    site: "Bouake",
    projectId: "PRJ-BKE-001",
    projectName: "RN3 Bouake-Katiola",
    title: "Actions critiques en retard de plus de 30 jours",
    source: "Plan actions HSE",
    severity: "Haute",
    status: "Ouvert",
    dueDate: "07/06/2026",
    owner: "M. Diallo",
    recommendation: "Escalader les actions critiques au responsable de site.",
  },
  {
    id: "alt-004",
    tenantId: "delta-mining",
    tenantName: "Delta Mining",
    moduleId: "inspections",
    moduleName: "Inspections",
    site: "Bouake",
    projectId: "PRJ-BKE-002",
    projectName: "Carriere Granite BKE Nord",
    title: "Conformite audit sous le seuil de 70%",
    source: "Audit terrain",
    severity: "Haute",
    status: "A verifier",
    dueDate: "08/06/2026",
    owner: "S. Traore",
    recommendation: "Programmer une contre-visite et controler les preuves de cloture.",
  },
  {
    id: "alt-005",
    tenantId: "delta-mining",
    tenantName: "Delta Mining",
    moduleId: "ppe",
    moduleName: "EPI",
    site: "Yamoussoukro",
    projectId: "PRJ-YMK-001",
    projectName: "Rehab. Infrastructures YMK",
    title: "Detecteurs gaz a recalibrer",
    source: "Controle periodique EPI",
    severity: "Moyenne",
    status: "En cours",
    dueDate: "12/06/2026",
    owner: "N. Kone",
    recommendation: "Planifier le recalibrage et isoler les detecteurs non conformes.",
  },
  {
    id: "alt-006",
    tenantId: "medlog-ci",
    tenantName: "Medlog CI",
    moduleId: "permits",
    moduleName: "Permis",
    site: "Abidjan",
    projectId: "PRJ-ABJ-002",
    projectName: "Tour Plateau Finance",
    title: "Permis espace confine sans validation HSE",
    source: "Permis dangereux",
    severity: "Critique",
    status: "Ouvert",
    dueDate: "04/06/2026",
    owner: "M. Diallo",
    recommendation: "Bloquer l'execution tant que la validation HSE n'est pas complete.",
  },
  {
    id: "alt-007",
    tenantId: "medlog-ci",
    tenantName: "Medlog CI",
    moduleId: "actions",
    moduleName: "Actions",
    site: "San Pedro",
    projectId: "PRJ-SPD-001",
    projectName: "Terminal Vraquiers SP",
    title: "Preuves de cloture manquantes",
    source: "Plan actions HSE",
    severity: "Haute",
    status: "A verifier",
    dueDate: "10/06/2026",
    owner: "A. Kouadio",
    recommendation: "Demander les preuves terrain avant passage en cloture.",
  },
  {
    id: "alt-008",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "duerp",
    moduleName: "DUERP",
    site: "Abidjan",
    projectId: "PRJ-ABJ-001",
    projectName: "Autoroute Abidjan-Bassam",
    title: "2 risques critiques DUERP non traites (criticite >= 50)",
    source: "Document Unique Evaluation Risques",
    severity: "Critique",
    status: "Ouvert",
    dueDate: "07/06/2026",
    owner: "A. Kouadio",
    recommendation: "Mettre en oeuvre immediatement les mesures de maitrise pour chute hauteur et risque electrique.",
  },
  {
    id: "alt-009",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "training",
    moduleName: "Formations",
    site: "Bouake",
    projectId: "PRJ-BKE-001",
    projectName: "RN3 Bouake-Katiola",
    title: "CACES R482 expire — 3 conducteurs engins sans habilitation valide",
    source: "Suivi habilitations",
    severity: "Critique",
    status: "Ouvert",
    dueDate: "06/06/2026",
    owner: "M. Diallo",
    recommendation: "Interdire la conduite aux conducteurs non habilites et planifier le recyclage en urgence.",
  },
  {
    id: "alt-010",
    tenantId: "delta-mining",
    tenantName: "Delta Mining",
    moduleId: "medical",
    moduleName: "Medical",
    site: "Bouake",
    projectId: "PRJ-BKE-002",
    projectName: "Carriere Granite BKE Nord",
    title: "Visites medicales en retard — 3 salaries exposes aux poussieres",
    source: "Suivi aptitudes medicales",
    severity: "Haute",
    status: "Ouvert",
    dueDate: "08/06/2026",
    owner: "S. Traore",
    recommendation: "Planifier les visites medicales periodiques avant retour poste exposition.",
  },
  {
    id: "alt-011",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "vbg",
    moduleName: "VBG",
    site: "Yamoussoukro",
    projectId: "PRJ-YMK-001",
    projectName: "Rehab. Infrastructures YMK",
    title: "Investigation VBG-YMK-003 non cloturee — delai WB 30j depasse",
    source: "Mecanisme signalement VBG",
    severity: "Critique",
    status: "En cours",
    dueDate: "08/06/2026",
    owner: "M. Diallo",
    recommendation: "Finaliser l'investigation et transmettre le rapport confidentiel a la coordinatrice VBG avant echeance.",
  },
  {
    id: "alt-012",
    tenantId: "medlog-ci",
    tenantName: "Medlog CI",
    moduleId: "consumption",
    moduleName: "Consommations",
    site: "Abidjan",
    projectId: "PRJ-ABJ-002",
    projectName: "Tour Plateau Finance",
    title: "Depassement objectif consommation eau — 3 mois consecutifs",
    source: "Suivi consommations environnementales",
    severity: "Haute",
    status: "A verifier",
    dueDate: "10/06/2026",
    owner: "A. Kouadio",
    recommendation: "Identifier les fuites et mettre en oeuvre les mesures de reduction avant le rapport mensuel.",
  },
  {
    id: "alt-013",
    tenantId: "acme-btp",
    tenantName: "ACME BTP",
    moduleId: "planification",
    moduleName: "Planification",
    site: "Abidjan",
    projectId: "PRJ-ABJ-001",
    projectName: "Autoroute Abidjan-Bassam",
    title: "Audit sous-traitants Q2 non realise — en retard de 15 jours",
    source: "Programme HSE annuel",
    severity: "Haute",
    status: "Ouvert",
    dueDate: "09/06/2026",
    owner: "A. Kouadio",
    recommendation: "Confirmer la date de l'audit sous-traitants avec le responsable HSE et reprogrammer.",
  },
];

export function getAlertsForTenant(tenantId?: string | null) {
  return tenantId ? hseAlerts.filter((alert) => alert.tenantId === tenantId) : hseAlerts;
}

export function getAlertSummary(alerts: HseAlert[]) {
  return {
    total: alerts.length,
    critical: alerts.filter((alert) => alert.severity === "Critique").length,
    high: alerts.filter((alert) => alert.severity === "Haute").length,
    open: alerts.filter((alert) => alert.status === "Ouvert").length,
  };
}
