export type TemplateColumn = {
  key: string;
  label: string;
  required: boolean;
  type: "texte" | "date" | "nombre" | "liste";
  values?: string[];
};

export type ModuleTemplate = {
  moduleId: string;
  filename: string;
  columns: TemplateColumn[];
};

const commonColumns: TemplateColumn[] = [
  { key: "site", label: "Site", required: true, type: "texte" },
  { key: "projet", label: "Projet", required: true, type: "texte" },
  { key: "service", label: "Service", required: false, type: "texte" },
  { key: "date", label: "Date", required: true, type: "date" },
  { key: "responsable", label: "Responsable", required: true, type: "texte" },
];

export const templates: Record<string, ModuleTemplate> = {
  events: {
    moduleId: "events",
    filename: "modele_evenements_hse.xlsx",
    columns: [
      ...commonColumns,
      { key: "type_evenement", label: "Type evenement", required: true, type: "liste", values: ["Accident", "Incident", "Presqu'accident"] },
      { key: "gravite", label: "Gravite", required: true, type: "liste", values: ["Faible", "Moyenne", "Elevee", "Critique"] },
      { key: "description", label: "Description", required: true, type: "texte" },
      { key: "cause_racine", label: "Cause racine", required: false, type: "texte" },
      { key: "statut", label: "Statut", required: true, type: "liste", values: ["Ouvert", "En cours", "Clos"] },
    ],
  },
  inspections: {
    moduleId: "inspections",
    filename: "modele_inspections_audits_hse.xlsx",
    columns: [
      ...commonColumns,
      { key: "type_controle", label: "Type controle", required: true, type: "liste", values: ["Inspection", "Audit", "Controle"] },
      { key: "theme", label: "Theme", required: true, type: "texte" },
      { key: "conformite", label: "Conformite", required: true, type: "liste", values: ["Conforme", "Non conforme", "Partiel"] },
      { key: "ecart", label: "Ecart observe", required: false, type: "texte" },
      { key: "preuve", label: "Preuve", required: false, type: "texte" },
    ],
  },
  permits: {
    moduleId: "permits",
    filename: "modele_permis_travail_dangereux.xlsx",
    columns: [
      ...commonColumns,
      { key: "type_permis", label: "Type permis", required: true, type: "liste", values: ["Travail a chaud", "Hauteur", "Espace confine", "Levage", "Electrique"] },
      { key: "zone", label: "Zone", required: true, type: "texte" },
      { key: "date_debut", label: "Date debut", required: true, type: "date" },
      { key: "date_fin", label: "Date fin", required: true, type: "date" },
      { key: "validation_hse", label: "Validation HSE", required: true, type: "liste", values: ["Oui", "Non"] },
    ],
  },
  actions: {
    moduleId: "actions",
    filename: "modele_plan_actions_hse.xlsx",
    columns: [
      ...commonColumns,
      { key: "origine", label: "Origine", required: true, type: "liste", values: ["Incident", "Audit", "Inspection", "Revue"] },
      { key: "action", label: "Action", required: true, type: "texte" },
      { key: "priorite", label: "Priorite", required: true, type: "liste", values: ["Basse", "Normale", "Haute", "Critique"] },
      { key: "echeance", label: "Echeance", required: true, type: "date" },
      { key: "statut", label: "Statut", required: true, type: "liste", values: ["Ouvert", "En cours", "Clos", "En retard"] },
    ],
  },
  indicators: {
    moduleId: "indicators",
    filename: "modele_indicateurs_hse_mensuels.xlsx",
    columns: [
      { key: "mois",   label: "Mois",   required: true, type: "texte" },
      { key: "site",   label: "Site",   required: true, type: "texte" },
      { key: "projet", label: "Projet", required: true, type: "texte" },
      { key: "heures_travaillees", label: "Heures travaillees", required: true, type: "nombre" },
      { key: "accidents_avec_arret", label: "Accidents avec arret", required: true, type: "nombre" },
      { key: "jours_perdus", label: "Jours perdus", required: true, type: "nombre" },
      { key: "causeries", label: "Causeries HSE", required: true, type: "nombre" },
      { key: "formations", label: "Formations HSE", required: true, type: "nombre" },
    ],
  },
  ppe: {
    moduleId: "ppe",
    filename: "modele_suivi_epi_equipements_securite.xlsx",
    columns: [
      { key: "site",        label: "Site",                          required: true,  type: "texte" },
      { key: "projet",      label: "Projet",                        required: true,  type: "texte" },
      { key: "reference",   label: "Reference",                     required: true,  type: "texte" },
      { key: "designation", label: "Designation EPI / Equipement",  required: true,  type: "texte" },
      {
        key: "categorie",
        label: "Categorie",
        required: true,
        type: "liste",
        values: [
          "Protection mains",
          "Protection voies respiratoires",
          "Visibilite",
          "Detection gaz",
          "Premiers secours",
          "Protection genoux",
          "Protection auditive",
          "Espace confine",
          "Protection tete",
          "Protection pieds",
          "Protection yeux",
        ],
      },
      { key: "norme", label: "Norme CE / Certification", required: true, type: "texte" },
      {
        key: "risque_couvert",
        label: "Risque Couvert",
        required: true,
        type: "liste",
        values: [
          "Coupure / abrasion",
          "Poussieres / aerosols",
          "Heurt engins",
          "Gaz toxique / explosif",
          "Blessures legeres",
          "Incendie",
          "Contusion",
          "Bruit fort",
          "Sauvetage",
        ],
      },
      { key: "quantite_stock", label: "Quantite Stock", required: true, type: "nombre" },
      { key: "quantite_attribuee", label: "Quantite Attribuee", required: true, type: "nombre" },
      { key: "quantite_disponible", label: "Quantite Disponible", required: true, type: "nombre" },
      { key: "date_achat", label: "Date Achat", required: true, type: "date" },
      { key: "date_expiration", label: "Date Expiration", required: true, type: "date" },
      {
        key: "controle_periodique",
        label: "Controle Periodique",
        required: true,
        type: "liste",
        values: ["Selon usure", "Usage unique", "Mensuel", "Hebdomadaire", "Semestriel", "Trimestriel", "Annuel", "Avant chaque usage"],
      },
      { key: "fournisseur", label: "Fournisseur", required: true, type: "texte" },
      { key: "cout_unitaire", label: "Cout Unit. (FCFA)", required: true, type: "nombre" },
      { key: "observations", label: "Observations", required: false, type: "texte" },
    ],
  },

  environment: {
    moduleId: "environment",
    filename: "modele_impacts_environnementaux.xlsx",
    columns: [
      { key: "code_projet",       label: "Code Projet",                  required: true,  type: "texte" },
      { key: "projet",            label: "Projet",                       required: true,  type: "texte" },
      { key: "site",              label: "Site",                         required: true,  type: "texte" },
      { key: "date_evaluation",   label: "Date evaluation (AAAA-MM-JJ)", required: true,  type: "date" },
      { key: "type_travaux",      label: "Type de travaux",              required: true,  type: "texte" },
      {
        key: "phase",
        label: "Phase",
        required: true,
        type: "liste",
        values: ["Preparation", "Construction", "Exploitation"],
      },
      { key: "impact",            label: "Impact environnemental",       required: true,  type: "texte" },
      {
        key: "milieu_affecte",
        label: "Milieu affecte",
        required: true,
        type: "liste",
        values: ["Sol", "Eau de surface", "Eau souterraine", "Air", "Bruit", "Biodiversite", "Dechets", "Paysage", "Population"],
      },
      { key: "intensite",         label: "Intensite (1-3)",              required: true,  type: "nombre" },
      { key: "portee",            label: "Portee (1-3)",                 required: true,  type: "nombre" },
      { key: "duree",             label: "Duree (1-3)",                  required: true,  type: "nombre" },
      { key: "mesures_attenuation", label: "Mesures d'attenuation",      required: true,  type: "texte" },
      { key: "responsable",       label: "Responsable",                  required: true,  type: "texte" },
      { key: "indicateur_suivi",  label: "Indicateur de suivi",          required: false, type: "texte" },
      {
        key: "statut",
        label: "Statut mesure",
        required: true,
        type: "liste",
        values: ["Planifie", "En cours", "Valide"],
      },
      { key: "echeance",          label: "Echeance traitement",          required: true,  type: "date" },
    ],
  },
  training: {
    moduleId: "training",
    filename: "modele_formations_habilitations.xlsx",
    columns: [
      { key: "nom",             label: "Nom",                  required: true,  type: "texte" },
      { key: "prenom",          label: "Prenom",               required: true,  type: "texte" },
      { key: "matricule",       label: "Matricule",            required: true,  type: "texte" },
      { key: "poste",           label: "Poste",                required: true,  type: "texte" },
      { key: "site",            label: "Site",                 required: true,  type: "texte" },
      { key: "projet",          label: "Projet",               required: true,  type: "texte" },
      { key: "type",            label: "Type", required: true, type: "liste",   values: ["Formation", "Habilitation", "Attestation", "Recyclage"] },
      { key: "titre",           label: "Titre formation/habilitation", required: true,  type: "texte" },
      { key: "organisme",       label: "Organisme formateur",  required: true,  type: "texte" },
      { key: "date_formation",  label: "Date de formation",    required: true,  type: "date" },
      { key: "date_expiration", label: "Date d'expiration",    required: false, type: "date" },
      { key: "document_ref",    label: "Reference document",   required: false, type: "texte" },
      { key: "statut",          label: "Statut", required: true, type: "liste", values: ["Valide", "A renouveler", "Expire", "En cours"] },
    ],
  },

  causeries: {
    moduleId: "causeries",
    filename: "modele_causeries_hse.xlsx",
    columns: [
      { key: "date",            label: "Date",                 required: true,  type: "date" },
      { key: "site",            label: "Site",                 required: true,  type: "texte" },
      { key: "projet",          label: "Projet",               required: true,  type: "texte" },
      { key: "animateur",       label: "Animateur",            required: true,  type: "texte" },
      { key: "theme",           label: "Theme",                required: true,  type: "texte" },
      { key: "type",            label: "Type", required: true, type: "liste",   values: ["Causerie", "Toolbox Talk", "Briefing securite", "Quart d'heure securite"] },
      { key: "duree_minutes",   label: "Duree (minutes)",      required: true,  type: "nombre" },
      { key: "nb_participants", label: "Nb participants",      required: true,  type: "nombre" },
      { key: "nb_prevus",       label: "Nb prevus",            required: true,  type: "nombre" },
      { key: "observations",    label: "Observations",         required: false, type: "texte" },
    ],
  },

  duerp: {
    moduleId: "duerp",
    filename: "modele_duerp_evaluation_risques.xlsx",
    columns: [
      { key: "site",              label: "Site",                         required: true,  type: "texte" },
      { key: "projet",            label: "Projet",                       required: true,  type: "texte" },
      { key: "date_evaluation",   label: "Date evaluation (AAAA-MM-JJ)", required: true,  type: "date" },
      { key: "unite_travail",     label: "Unite de travail",             required: true,  type: "texte" },
      { key: "activite",          label: "Activite",                     required: true,  type: "texte" },
      { key: "danger",            label: "Danger",                       required: true,  type: "texte" },
      { key: "risque",            label: "Risque",                       required: true,  type: "texte" },
      { key: "frequence",         label: "Frequence (1-5)",              required: true,  type: "nombre" },
      { key: "gravite",           label: "Gravite (1-5)",                required: true,  type: "nombre" },
      { key: "probabilite",       label: "Probabilite (1-5)",            required: true,  type: "nombre" },
      { key: "mesures_existantes", label: "Mesures existantes",          required: false, type: "texte" },
      { key: "mesures_prevues",   label: "Mesures prevues",              required: false, type: "texte" },
      { key: "responsable",       label: "Responsable",                  required: true,  type: "texte" },
      { key: "echeance",          label: "Echeance traitement",          required: true,  type: "date" },
      { key: "statut",            label: "Statut", required: true, type: "liste", values: ["Non traite", "En cours de traitement", "Maitrise"] },
    ],
  },

  medical: {
    moduleId: "medical",
    filename: "modele_visites_medicales.xlsx",
    columns: [
      { key: "nom",             label: "Nom",                  required: true,  type: "texte" },
      { key: "prenom",          label: "Prenom",               required: true,  type: "texte" },
      { key: "matricule",       label: "Matricule",            required: true,  type: "texte" },
      { key: "poste",           label: "Poste",                required: true,  type: "texte" },
      { key: "site",            label: "Site",                 required: true,  type: "texte" },
      { key: "projet",          label: "Projet",               required: true,  type: "texte" },
      { key: "type_visite",     label: "Type visite", required: true, type: "liste", values: ["Embauche", "Periodique", "Reprise", "Spontanee", "Pre-reprise"] },
      { key: "date_visite",     label: "Date de visite",       required: true,  type: "date" },
      { key: "date_prochaine",  label: "Date prochaine visite",required: true,  type: "date" },
      { key: "medecin",         label: "Medecin",              required: false, type: "texte" },
      { key: "aptitude",        label: "Aptitude", required: true, type: "liste", values: ["Apte", "Apte avec restrictions", "Inapte temporaire", "Inapte definitif"] },
      { key: "restrictions",    label: "Restrictions medicales",required: false, type: "texte" },
      { key: "observations",    label: "Observations",         required: false, type: "texte" },
    ],
  },

  acr: {
    moduleId: "acr",
    filename: "modele_analyses_causes_racines.xlsx",
    columns: [
      { key: "evenement_ref",    label: "Reference evenement",  required: true,  type: "texte" },
      { key: "date_evenement",   label: "Date evenement",       required: true,  type: "date" },
      { key: "site",             label: "Site",                 required: true,  type: "texte" },
      { key: "projet",           label: "Projet",               required: true,  type: "texte" },
      { key: "type_evenement",   label: "Type evenement",       required: true,  type: "texte" },
      { key: "description",      label: "Description",          required: true,  type: "texte" },
      { key: "methode",          label: "Methode ACR", required: true, type: "liste", values: ["5 Pourquoi", "Arbre des causes", "Ishikawa", "ORION"] },
      { key: "causes_immediates",label: "Causes immediates",    required: true,  type: "texte" },
      { key: "causes_profondes", label: "Causes profondes",     required: false, type: "texte" },
      { key: "responsable",      label: "Responsable analyse",  required: true,  type: "texte" },
      { key: "date_analyse",     label: "Date analyse",         required: true,  type: "date" },
      { key: "lecons_apprises",  label: "Lecons apprises",      required: false, type: "texte" },
      { key: "statut",           label: "Statut", required: true, type: "liste", values: ["En cours", "Finalise", "Actions lancees", "Cloture"] },
    ],
  },

  consumption: {
    moduleId: "consumption",
    filename: "modele_consommations_environnementales.xlsx",
    columns: [
      { key: "mois",                  label: "Mois (AAAA-MM)",       required: true,  type: "texte" },
      { key: "site",                  label: "Site",                 required: true,  type: "texte" },
      { key: "projet",                label: "Projet",               required: true,  type: "texte" },
      { key: "eau_m3",                label: "Eau (m3)",             required: true,  type: "nombre" },
      { key: "electricite_kwh",       label: "Electricite (kWh)",    required: true,  type: "nombre" },
      { key: "carburant_litres",      label: "Carburant (litres)",   required: true,  type: "nombre" },
      { key: "dechets_tonnes",        label: "Dechets inertes (t)",  required: false, type: "nombre" },
      { key: "dechets_dangereux_kg",  label: "Dechets dangereux (kg)",required: false, type: "nombre" },
      { key: "co2_tonnes",            label: "CO2 emis (tonnes)",    required: false, type: "nombre" },
      { key: "objectif_eau",          label: "Objectif eau (m3)",    required: false, type: "nombre" },
      { key: "objectif_electricite",  label: "Objectif elec (kWh)",  required: false, type: "nombre" },
      { key: "objectif_carburant",    label: "Objectif carb (L)",    required: false, type: "nombre" },
    ],
  },

  planification: {
    moduleId: "planification",
    filename: "modele_programme_planification_hse.xlsx",
    columns: [
      { key: "trimestre",      label: "Trimestre",            required: true,  type: "liste",  values: ["T1", "T2", "T3", "T4"] },
      { key: "mois",           label: "Mois",                 required: true,  type: "texte" },
      { key: "categorie",      label: "Categorie", required: true, type: "liste", values: ["Formation", "Audit", "Inspection", "EPI", "Medical", "Exercice", "DUERP", "Bilan"] },
      { key: "activite",       label: "Activite",             required: true,  type: "texte" },
      { key: "responsable",    label: "Responsable",          required: true,  type: "texte" },
      { key: "site",           label: "Site",                 required: true,  type: "texte" },
      { key: "projet",         label: "Projet",               required: true,  type: "texte" },
      { key: "budget_fcfa",    label: "Budget (FCFA)",        required: true,  type: "nombre" },
      { key: "statut",         label: "Statut", required: true, type: "liste", values: ["Realisee", "En cours", "Planifiee", "En retard"] },
      { key: "commentaire",    label: "Commentaire",          required: false, type: "texte" },
    ],
  },
  vbg: {
    moduleId: "vbg",
    filename: "modele_vbg_eas_hs.xlsx",
    columns: [
      { key: "reference",       label: "Reference (anonymisee)", required: true,  type: "texte" },
      { key: "date",            label: "Date de l'incident",     required: true,  type: "date" },
      { key: "site",            label: "Site",                   required: true,  type: "liste", values: ["Abidjan", "Bouake", "San Pedro", "Yamoussoukro"] },
      { key: "projet",          label: "Projet",                 required: true,  type: "texte" },
      { key: "type_vbg",        label: "Type VBG", required: true, type: "liste", values: ["Harcelement sexuel", "Violence physique", "Violence psychologique", "Exploitation et abus sexuels (EAS)", "Discrimination fondee sur le genre", "Traite des personnes", "Violence domestique", "Autre"] },
      { key: "auteur_allegue",  label: "Auteur allégué", required: true, type: "liste", values: ["Travailleur", "Superviseur / Cadre", "Sous-traitant", "Tiers / Communaute", "Non identifie"] },
      { key: "gravite",         label: "Gravite", required: true, type: "liste", values: ["Mineur", "Modere", "Grave", "Tres grave"] },
      { key: "statut",          label: "Statut", required: true, type: "liste", values: ["Signale", "En investigation", "Resolu", "Cloture", "Non fonde", "Refere"] },
      { key: "signale_par",     label: "Signale par", required: true, type: "liste", values: ["Victime", "Temoin", "Superviseur", "Anonyme"] },
      { key: "canal_signalement", label: "Canal de signalement", required: false, type: "liste", values: ["Boite a plaintes", "Ligne directe", "Point focal VBG", "Application mobile", "Responsable HSE", "Direct"] },
      { key: "delai_resolution", label: "Delai de resolution (jours)", required: false, type: "nombre" },
      { key: "mesures_prises",  label: "Mesures prises",         required: false, type: "texte" },
      { key: "norme_reference", label: "Norme de reference", required: false, type: "texte" },
    ],
  },
};

export function getTemplate(moduleId: string) {
  return templates[moduleId];
}
