export type ModuleRecord = {
  id: string;
  moduleId: string;
  date: string;
  site: string;
  entity: string;
  label: string;
  category: string;
  owner: string;
  status: "Ouvert" | "En cours" | "Clos" | "A corriger" | "Valide";
  priority: "Basse" | "Normale" | "Haute" | "Critique";
  dueDate: string;
};

export const moduleRecords: ModuleRecord[] = [
  {
    id: "evt-001",
    moduleId: "events",
    date: "02/06/2026",
    site: "Bouake",
    entity: "Site Bouake",
    label: "Incident levage sans dommage",
    category: "Incident",
    owner: "S. Traore",
    status: "En cours",
    priority: "Haute",
    dueDate: "08/06/2026",
  },
  {
    id: "evt-002",
    moduleId: "events",
    date: "30/05/2026",
    site: "Abidjan",
    entity: "Site Abidjan",
    label: "Presqu'accident circulation engin",
    category: "Presqu'accident",
    owner: "A. Kouadio",
    status: "Ouvert",
    priority: "Critique",
    dueDate: "05/06/2026",
  },
  {
    id: "ins-001",
    moduleId: "inspections",
    date: "31/05/2026",
    site: "San Pedro",
    entity: "Projet San Pedro",
    label: "Audit stockage produits chimiques",
    category: "Audit",
    owner: "N. Kone",
    status: "A corriger",
    priority: "Haute",
    dueDate: "10/06/2026",
  },
  {
    id: "ins-002",
    moduleId: "inspections",
    date: "28/05/2026",
    site: "Yamoussoukro",
    entity: "Site Yamoussoukro",
    label: "Inspection port EPI zone coffrage",
    category: "Inspection",
    owner: "M. Diallo",
    status: "Clos",
    priority: "Normale",
    dueDate: "02/06/2026",
  },
  {
    id: "per-001",
    moduleId: "permits",
    date: "01/06/2026",
    site: "Abidjan",
    entity: "Site Abidjan",
    label: "Travail a chaud atelier maintenance",
    category: "Travail a chaud",
    owner: "A. Kouadio",
    status: "Valide",
    priority: "Haute",
    dueDate: "01/06/2026",
  },
  {
    id: "per-002",
    moduleId: "permits",
    date: "29/05/2026",
    site: "Bouake",
    entity: "Site Bouake",
    label: "Intervention espace confine cuve",
    category: "Espace confine",
    owner: "S. Traore",
    status: "A corriger",
    priority: "Critique",
    dueDate: "04/06/2026",
  },
  {
    id: "act-001",
    moduleId: "actions",
    date: "27/05/2026",
    site: "Bouake",
    entity: "Site Bouake",
    label: "Installer garde-corps provisoires",
    category: "Action corrective",
    owner: "M. Diallo",
    status: "En cours",
    priority: "Critique",
    dueDate: "06/06/2026",
  },
  {
    id: "act-002",
    moduleId: "actions",
    date: "25/05/2026",
    site: "San Pedro",
    entity: "Projet San Pedro",
    label: "Former equipe levage aux signaux",
    category: "Action preventive",
    owner: "N. Kone",
    status: "Ouvert",
    priority: "Haute",
    dueDate: "12/06/2026",
  },
  {
    id: "ind-001",
    moduleId: "indicators",
    date: "31/05/2026",
    site: "Abidjan",
    entity: "Site Abidjan",
    label: "Reporting mensuel mai",
    category: "Indicateurs mensuels",
    owner: "S. Traore",
    status: "Valide",
    priority: "Normale",
    dueDate: "03/06/2026",
  },
  {
    id: "ind-002",
    moduleId: "indicators",
    date: "31/05/2026",
    site: "Bouake",
    entity: "Site Bouake",
    label: "Heures travaillees a completer",
    category: "Donnees manquantes",
    owner: "M. Diallo",
    status: "A corriger",
    priority: "Haute",
    dueDate: "04/06/2026",
  },
  {
    id: "ppe-001",
    moduleId: "ppe",
    date: "02/06/2026",
    site: "San Pedro",
    entity: "Projet San Pedro",
    label: "Masques FFP3 a commander",
    category: "Voies respiratoires",
    owner: "K. Yao",
    status: "Ouvert",
    priority: "Critique",
    dueDate: "05/06/2026",
  },
  {
    id: "ppe-002",
    moduleId: "ppe",
    date: "01/06/2026",
    site: "Abidjan",
    entity: "Site Abidjan",
    label: "Controle detecteurs gaz",
    category: "Detection gaz",
    owner: "A. Kouadio",
    status: "En cours",
    priority: "Haute",
    dueDate: "07/06/2026",
  },
];

export function getModuleRecords(moduleId: string) {
  return moduleRecords.filter((record) => record.moduleId === moduleId);
}
